server.port=8080
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# External Company Store API
app.external-store.enabled=false
app.external-store.url=
app.external-store.api-key=

# Points configuration
app.points.peer-giving-allowance=20
app.points.team-giving-allowance=20
app.points.allow-self-team-award=false
