server.port=8080
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# External Company Store API
app.external-store.enabled=false
app.external-store.url=
app.external-store.api-key=
